### ISSUE TITLE
Error on ubuntu

### ISSUE THREAD

**Issue by ajouve** [AnsibleShipyard/ansible-nodejs#20]
TASK: [JasonGiedymin.nodejs | Install Debian packages] ************************
failed: [default] => (item=wget,curl,make,g++,gcc,libcurl4-openssl-dev,libsasl2-2,libsasl2-dev,libcurl3) => {"failed": true, "item": "wget,curl,make,g++,gcc,libcurl4-openssl-dev,libsasl2-2,libsasl2-dev,libcurl3"}
msg: Failed to lock apt for exclusive operation

**Comment by JasonGiedymin** [comment]
I've added travis-ci file and bumped the version. All pass. See: 

https://travis-ci.org/AnsibleShipyard/ansible-nodejs/builds/48843939

Travis-ci uses Ubuntu.
